---
- hosts: qa
  become: yes
  tasks: 
       - name : start Docker service 
         service: 
            name: Docker 
            state: started 
       - name: "pull docker image"
         docker_image:
            name: bloomytech/my-webpage
            source: pull
            command: docker pull bloomytech/my-webpage
            
            
       - name: Run Docker container using simple-docker-image
         docker_container:
            name: Kitchensinkapp
            image: bloomytech/my-webpage
            state: started
            recreate: yes
            detach: true
            ports:
              - "8888:8080"
