---
- hosts: qa
  become: yes
  tasks: 
       - name : start Docker service 
         service: 
            name: Docker 
            state: started 
       - name: "pull docker image"
         docker_image:
            name: learndevops083/Kitchensinkapp
            command: docker pull learndevops083/Kitchensinkapp
            
       - name: Run Docker container using simple-docker-image
         docker_container:
            name: Kitchensinkapp
            source: pull
            image: learndevops083/Kitchensinkapp
            state: started
            recreate: yes
            detach: true
            ports:
              - "8888:8080"
